const mots = [
  "avocat",
  "boulanger",
  "cafetière",
  "chaîne",
  "citrouille",
  "classement",
  "colère",
  "couleur",
  "crise",
  "cuisine",
  "devoir",
  "diplomatie",
  "dizaine",
  "dix",
  "docteur",
  "dommage",
  "dominion",
  "douceur",
  "drôle",
  "duel",
  "effort",
  "émotion",
  "encore",
  "envie",
  "erreur",
  "essayer",
  "expérience",
  "facile",
  "faible",
  "facteur",
  "faim",
  "fermeture",
  "fin",
  "flotte",
  "fourchette",
  "français",
  "formule",
  "fortune",
  "frustration",
  "gâteau",
  "gentillesse",
  "glace",
  "grandeur",
  "grand-père",
  "grammaire",
  "grapefruit",
  "guerre",
  "habit",
  "hallucination",
  "halte",
  "harmonie",
  "herbe",
  "idée",
  "inconvénient",
  "indication",
  "intérêt",
  "interprétation",
  "invitation",
  "invention",
  "jalousie",
  "journée",
  "justice",
  "kiss",
  "langage",
  "laurier",
  "lettre",
  "licorne",
  "ligne",
  "liste",
  "long",
  "maintenance",
  "maladie",
  "manifestation",
  "mappe",
  "matinée",
  "maison",
  "médecin",
  "moelle",
  "monde",
  "motivation",
  "musicienne",
  "navette",
  "noël",
  "nombre",
  "notoriété",
  "novel",
  "nuage",
  "obstacle",
  "objet",
  "objectif",
  "occurrence",
  "offrande",
  "opportunité",
  "ordinateur",
  "organisme",
  "origine",
  "oscillation",
  "ours",
  "pacificateur",
  "panne",
  "passion",
  "paume",
  "phare",
  "pièce",
  "piscine",
  "place",
  "plant",
  "playlist",
  "podcast",
  "polaroid",
  "portrait",
  "poster",
  "puissance",
  "publiquement",
  "publicité",
  "purpose",
  "qualité",
  "quantité",
  "question",
  "réalité",
  "règle",
  "restaurant",
  "roman",
  "rose",
  "rubrique",
  "ruche",
  "rugby",
  "rumour",
  "rythme",
  "salade",
  "science",
  "sculpture",
  "secrecy",
  "service",
  "session",
  "soirée",
  "sonnet",
  "spaghetti",
  "speech",
  "structure",
  "style",
  "surprise",
  "syllogisme",
  "synergie",
  "talent",
  "technologie",
  "terre",
  "theatre",
  "tigre",
  "trait",
  "trouble",
  "triangle",
  "tuition",
  "université",
  "utilisation",
  "valeur",
  "vision",
  "volcan",
  "voiture",
  "vélo",
  "vente",
  "vernis",
  "vidéo",
  "ville",
  "vin",
  "visiteur",
  "visionnaire",
  "vocaliste",
  "volume",
  "wifi",
  "xylophone",
  "yeux",
  "zéro",
  
];
const div = document.querySelector('#sugg');
const input = document.querySelector('input');
input.addEventListener('input', (e)=> {
  //console.log(e.target.value);
  //console.log(input.value);
  const results = search(e.target.value, mots);
  console.log(results);
  let liste = "";
   for(let i = 0; i < results.length; i++){
    liste += "<li>" + results[i] + "</li>"
   
  }
   div.innerHTML = liste
})

const search = (str, wordList)=>{
  const results = [];
  if(str.length === 0){
    return results;
  }
  for(let i = 0; i < wordList.length ; i++){
    const item = wordList[i];
    if(item.startsWith(str)) {
      results.push(item)
    }
  }
  return results
}

